version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:8000"  # API
      - "6381:6381"  # Redis
    volumes:
      - ./article_exports:/app/article_exports
      - ./analysis_outputs:/app/analysis_outputs
      - ./logs:/app/logs
    environment:
      - ENV=production
      - REDIS_HOST=127.0.0.1
      - REDIS_PORT=6381
      - REDIS_DB=0
      - POLLING_INTERVAL=120
      - ARTICLES_BUFFER_SIZE=15 